#!/bin/bash

# Run all smoke tests with a filename of smoke_*.
# * Exit code indicates overall number of test failures.
# * Each test is piped to "sponge" to print output all at once
#   when the test run is finished, for better reports.

FAILURES=0
pids=()

function print_debug() {
    echo
    echo "========================================"
    echo "Describe pods:"
    echo
    kubectl describe pods -n lightbend
    echo
    echo "========================================"
    echo
}

print_debug

for smoketest in smoke_*; do
	echo ==== Running $smoketest

	./$smoketest > /tmp/log-$smoketest &
	pids+=($!)
	smoketests+=($smoketest)
done

for (( n=0; n<${#pids[@]}; n++ )); do
    pid="${pids[$n]}"
    smoketest="${smoketests[$n]}"

    echo -n "Waiting for $smoketest to finish... "
    wait "$pid"
    r=$?
	((FAILURES+=$r))
	if [ "$r" == "0" ]; then
	    echo "done"
	else
	    echo "failed"
	    cat /tmp/log-$smoketest
	fi
done
echo

echo "All tests completed with $FAILURES failures"

if [ "$FAILURES" != "0" ]; then
    print_debug
fi

exit $FAILURES
