#!/bin/bash

## Test access to services via NodePort and nginx location directives.

if [[ ! $context  ]]; then
  source smokecommon
fi

#set -x

# Base URLs for access via NodePort setup
CONSOLE_NODE_BASE=$( busy_wait nodeport expose-es-console )
GRAFANA_NODE_BASE=$( busy_wait nodeport expose-grafana )
PROM_NODE_BASE=$( busy_wait nodeport expose-prometheus )
ALERTMGR_NODE_BASE=$( busy_wait nodeport expose-alertmanager )

# Base URLs for access to services via console using nginx location directives
GRAFANA_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/grafana
PROMETHEUS_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/prometheus
ESMONITOR_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/es-monitor-api

# Now run our tests
test_es_console_responding $CONSOLE_NODE_BASE
test_grafana_responding $GRAFANA_NODE_BASE
test_prom_responding $PROM_NODE_BASE
test_alertmanager_responding $ALERTMGR_NODE_BASE

test_grafana_responding $GRAFANA_VIA_CONSOLE
test_prom_responding $PROMETHEUS_VIA_CONSOLE
test_es_monitor_API_responding $ESMONITOR_VIA_CONSOLE

# ...and dump the summary
test_summary
