#!/bin/bash

## Test access to services via NodePort and nginx location directives.

source smokecommon

#set -x

# Base URL for access via NodePort setup
CONSOLE_NODE_BASE=$( busy_wait nodeport expose-es-console )

# Base URLs for access to services via console using nginx location directives
GRAFANA_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/grafana
PROMETHEUS_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/prometheus
ESMONITOR_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/es-monitor-api
ALERTMANAGER_VIA_CONSOLE=${CONSOLE_NODE_BASE}/service/alertmanager

# Now run our tests
test_es_console_responding $CONSOLE_NODE_BASE

test_grafana_responding $GRAFANA_VIA_CONSOLE
test_prom_responding $PROMETHEUS_VIA_CONSOLE
test_es_monitor_API_responding $ESMONITOR_VIA_CONSOLE
test_alertmanager_responding $ALERTMANAGER_VIA_CONSOLE

# ...and dump the summary
test_summary
