#!/bin/bash

# Run all smoke tests with a filename of smoke_*.
# Exit code indicates overall number of test failures.

#set -x

FAILURES=0
pids=()

for smoketest in smoke_*; do
	echo ==== Running $smoketest
	./$smoketest &
	pids+=($!)
done

for pid in "${pids[@]}"; do
	wait "$pid"
	((FAILURES+=$?))
done

echo "All tests completed with $FAILURES failures"

exit $FAILURES
