#!/bin/bash

# Run all smoke tests with a filename of smoke_*.
# * Exit code indicates overall number of test failures.
# * Each test is piped to "sponge" to print output all at once
#   when the test run is finished, for better reports.

FAILURES=0
pids=()

func print_debug() {
    echo
    echo "========================================"
    echo "Describe pods:"
    echo
    kubectl describe pods -n lightbend
    echo
    echo "========================================"
    echo
}

print_debug

for smoketest in smoke_*; do
	echo ==== Running $smoketest

	./$smoketest
	((FAILURES+=$?))
done

echo "All tests completed with $FAILURES failures"

if [ "$FAILURES" != "0" ]; then
    print_debug
fi

exit $FAILURES
