# Example Lightbend Console Alertmanager config.

global:

# Routing rules.
route:
  receiver: slack
  # Resend unresolved alerts at this interval.
  repeat_interval: 4h
  # Wait for any other alerts in the same group before sending.
  group_wait: 30s
  # Wait before sending a new alert for a group.
  group_interval: 5m
  # Group alerts by namespace and workload.
  group_by: [namespace, es_workload]
  routes:
  - match:
      severity: warning
    receiver: slack
  - match:
      severity: critical
    receiver: slack
    continue: true
  - match:
      severity: critical
    receiver: pagerduty

# Don't alert on warnings if the same alert is already critical.
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal: [alertname]

templates:
# Slack notification templates.
- '/etc/config/slack.tmpl'

# Receivers.
receivers:
- name: slack
  slack_configs:
  # Use Slack integrations to find the webhook.
  - api_url: https://slack.localhost/services/somewhere
    channel: '#my-alerts'
    title: '{{ template "title.slack" . }}'
    text: '{{ template "text.slack" . }}'
    send_resolved: true

- name: pagerduty
  pagerduty_configs:
  - url: https://pagerduty.localhost/api
    routing_key: my_secret_routing_key
    service_key: my_secret_service_key
