{{ if .Values.createAlertManager }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager

spec:
  ports:
  - name: http
    port: 9093
    targetPort: 9093
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: alertmanager
  type: ClusterIP
{{ end }}
