{{ if .Values.createAlertManager }}
apiVersion: {{ .Values.deploymentApiVersion }}
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
spec:
  replicas: 1

  strategy:
    # Always Recreate to ensure the PVs get released. It's not possible to have two replicas sharing a PV during deployment.
    type: Recreate
    # Needed for helm upgrade to succeed.
    rollingUpdate: null

  selector:
    matchLabels:
      app: prometheus
      component: alertmanager
  template:
    metadata:
      labels:
        app: prometheus
        component: alertmanager
    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}
      serviceAccountName: default
      containers:
        - name: prometheus-alertmanager
          image: {{ .Values.alertManagerImage }}:{{ .Values.alertManagerVersion }}
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.alertManagerCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.alertManagerMemoryRequest }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data
            - --cluster.listen-address=$(POD_IP):6783
            {{ if .Values.esConsoleURL -}}
            - --web.external-url={{ .Values.esConsoleURL }}/service/alertmanager
            - --web.route-prefix=/
            {{ end }}
          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            timeoutSeconds: 30
            initialDelaySeconds: 30

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data

        - name: prometheus-alertmanager-configmap-reload
          image: {{ .Values.configMapReloadImage }}:{{ .Values.configMapReloadVersion }}
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.configmapReloadCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.configmapReloadMemoryRequest }}
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9093/-/reload
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.alertManagerConfigMap }}
        - name: data-volume
          {{ if or .Values.usePersistentVolumes (not .Values.useEmptyDirVolumes) }}
          persistentVolumeClaim:
            claimName: alertmanager-storage
          {{ else }}
          emptyDir: {}
          {{ end }}
{{ end }}
