{{ if .Values.createAlertManager }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  ports:
  - name: http
    port: 9093
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
  type: ClusterIP
{{ end }}
