{{ if .Values.createAlertManager }}
apiVersion: {{ .Values.coreApiVersion }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager
  name: alertmanager-default
data:
{{ (.Files.Glob "alertmanager/*").AsConfig | indent 2}}
{{ end }}
