apiVersion: v1
kind: Service
metadata:
  name: console-api
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8180
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: console-backend
