apiVersion: v1
kind: Service
metadata:
  name: console-api
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    com.lightbend.cloudflow/instance-id: {{ .Release.Name }}
    app.kubernetes.io/component: console-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8180
    - name: elasticsearch
      port: 9200
      targetPort: 9200
    - name: kibana
      port: 5601
      targetPort: 5601
    - name: logstash-tcp
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: logstash-udp
      port: 5000
      targetPort: 5000
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: console-backend
