apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console-backend
  name: bare-prometheus
data:
  prometheus.yml: |-
    # this is a placeholder to keep prometheus running while it awaits the real config
    global:
      scrape_interval:     99m
      evaluation_interval: 99m
    scrape_configs:
      - job_name: wait
        static_configs:
          - targets: ['localhost:9090']
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: .+
          action: drop
