
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-console
spec:
  template:
    metadata:
      labels:
        run: es-console
    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}
      containers:
      - name: dnsmasq
        image: "janeczku/go-dnsmasq:release-1.0.7"
        args:
          - --listen
          - "127.0.0.1:5353"
          - --verbose
          - --enable-search
      - name: es-console
        image: lightbend-docker-registry.bintray.io/enterprise-suite/es-console:{{ .Values.esConsoleVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ default .Values.defaultCPURequest .Values.esConsoleCPURequest }}
            memory: {{ default .Values.defaultMemoryRequest .Values.esConsoleMemoryRequest }}
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: es-console

{{ if .Values.minikube }}
---
apiVersion: v1
kind: Service
metadata:
  name: expose-es-console
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    run: es-console
  type: NodePort
{{ end }}

---
apiVersion: v1
kind: Service
metadata:
  name: console-server
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: es-console
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-console
data:
  default.conf: |-
    server {
      listen 8080;
      server_name localhost;
      set $base /usr/share/nginx/html;

      # use external resolver to lookup backends, cache for 30 seconds

      resolver 127.0.0.1:5353 ipv6=off valid=30s;

      set $prometheus "prometheus-server.{{.Release.Namespace}}.svc.cluster.local.";
      set $monitorapi "es-monitor-api.{{.Release.Namespace}}.svc.cluster.local.";
      set $grafana "grafana-server.{{.Release.Namespace}}.svc.cluster.local.";

      # proxy_pass backends with dynamic base url
      # (redirects to ' $1/' with a space prefix tells nginx to not add server and port)

      sub_filter_once off;

      location ~ (.*/service/prometheus)(/.*) {
        proxy_pass http://$prometheus$2$is_args$args;
        sub_filter '="/' '="$1/';
        sub_filter 'PATH_PREFIX = ""' 'PATH_PREFIX = "$1"';
        proxy_redirect '/' ' $1/';
      }

      location ~ (.*/service/es-monitor-api)(/.*) {
        proxy_pass http://$monitorapi$2$is_args$args;
        proxy_redirect '/' ' $1/';
      }

      location ~ (.*/service/grafana)(/.*) {
        proxy_pass http://$grafana:3000$2$is_args$args;
        sub_filter_types *;
        sub_filter '/service/grafana' '$1';
        proxy_cookie_path '/service/grafana' '$1';
        proxy_redirect '/' ' $1/';
      }

      # our injected plugin should never cache...
      location ~ (.*/service/grafana)(/dashboard/script/exporter-async.js) {
        proxy_pass http://$grafana:3000$2$is_args$args;
        sub_filter_types *;
        sub_filter '/service/grafana' '$1';
        proxy_cookie_path '/service/grafana' '$1';
        proxy_redirect '/' ' $1/';
        # no-cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      }

      # redirect /service/prometheus -> /service/prometheus/

      location ~ (.*/service/(prometheus|grafana))$ {
        return 301 ' $1/';
      }

      # console entry point

      location ~ (.*/)index.html {
        alias $base/index.html;
        sub_filter 'base href="/"' 'base href="$1"';
        # no-cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      }

      # bookmarks / reloads in the /workloads/ path
      # (for our single page app, these should reload index.html but keep the path)

      location ~ (.*)(/workloads/.*) {
        alias $base/index.html;
        default_type text/html;
        sub_filter 'base href="/"' 'base href="$1"';
        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
      }

      # static files

      location ~ (.*)(/assets/.*) {
        alias $base$2;
      }

      location ~ (.*)(/.*) {
        root $base;
        index index.html;
        try_files $2 $1/index.html;
      }

    }
