apiVersion: v1
kind: Service
metadata:
  name: console-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: es-console
  type: ClusterIP
