
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-console
spec:
  template:
    metadata:
      labels:
        run: es-console
    spec:
      containers:
      - name: es-console
        image: lightbend-docker-registry.bintray.io/enterprise-suite/es-console:{{ .Values.esConsoleVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: es-console

{{ if or .Values.minikube .Values.exposeConsoleService }}

---
apiVersion: v1
kind: Service
metadata:
  name: expose-es-console
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    run: es-console
  type: NodePort

{{ else }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-console
    component: "server"
  name: es-console-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: es-console
    component: "server"
  type: "ClusterIP"

{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-console
data:
  default.conf: |-
    server {
      listen 80;
      server_name localhost;

      location / {
        root  /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri$args $uri$args/ /index.html;
      }

      location /service/prometheus/ {
        proxy_pass http://prometheus-server/;
      }

      location /service/es-monitor-api/ {
        proxy_pass http://es-monitor-api/;
      }

      location /service/grafana/ {
        proxy_pass http://grafana-server:3000/;
      }

    }
