apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-console
spec:
  template:
    metadata:
      labels:
        run: es-console
    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}

      imagePullSecrets:
      - name: commercial-credentials

      initContainers:
      - name: setup-nginx-dns
        image: {{ .Values.alpineImage }}:{{ .Values.alpineVersion }}
        resources:
          requests:
            cpu: {{ default .Values.defaultCPURequest }}
            memory: {{ default .Values.defaultMemoryRequest }}
        command:
        - /bin/sh
        - -c
        args:
        - >-
          apk add gettext &&
          export KUBE_RESOLVER=$(awk '$1 == "nameserver" { print $2 }' /etc/resolv.conf) &&
          export KUBE_CONSOLE_DOMAIN=$(awk '$1 == "search" { print $2 }' /etc/resolv.conf) &&
          echo "resolver=$KUBE_RESOLVER console_domain=$KUBE_CONSOLE_DOMAIN" &&
          cat /template/default.conf | envsubst '$KUBE_RESOLVER $KUBE_CONSOLE_DOMAIN' > /etc/nginx/conf.d/default.conf &&
          echo "done templating /etc/nginx/conf.d/default.conf"

        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
          - name: nginx-template
            mountPath: /template

        {{ if .Values.podUID }}
        # Run init container as root so it can install gettext. This should be okay since it's a transient one-off
        # container without any external access.
        securityContext:
          runAsUser: 0
        {{ end }}

      containers:
      - name: es-console
        image: {{ tpl .Values.esConsoleImage . }}:{{ .Values.esConsoleVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ default .Values.defaultCPURequest .Values.esConsoleCPURequest }}
            memory: {{ default .Values.defaultMemoryRequest .Values.esConsoleMemoryRequest }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: config-volume
        emptyDir: {}
      - name: nginx-template
        configMap:
          name: es-console
