---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-demo
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: es-demo
    spec:
      containers:
        - name: es-demo
          image: lightbend-docker-registry.bintray.io/enterprise-suite/es-demo:{{ .Values.esDemoVersion }}
          ports:
            - containerPort: 9001
              name: metrics

