{{ if .Values.usePersistentVolumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-grafana-storage
spec:
  {{ if or .Values.defaultStorageClass .Values.esGrafanaStorageClass }}
  storageClassName: {{ default .Values.defaultStorageClass .Values.esGrafanaStorageClass }}
  {{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.esGrafanaVolumeSize }}
{{ end }}
