{{ if .Values.managePersistentVolumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-grafana-storage
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ default .Values.defaultStorageClass .Values.esGrafanaStorageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.esGrafanaVolumeSize }}
{{ end }}
