{{ if .Values.usePersistentVolumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-grafana-storage
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
spec:
  {{ if or .Values.defaultStorageClass .Values.esGrafanaStorageClass }}
  storageClassName: {{ default .Values.defaultStorageClass .Values.esGrafanaStorageClass }}
  {{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.esGrafanaVolumeSize }}
{{ end }}
