apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-state-metrics
  annotations:
    {{ .Values.prometheusDomain }}/scrape: "true"
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: kube-state-metrics
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
    component: "kube-state-metrics"
  type: "ClusterIP"
