apiVersion: {{ .Values.rbacApiVersion }}
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Namespace}}:kube-state-metrics
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    com.lightbend.cloudflow/instance-id: {{ .Release.Name }}
    app.kubernetes.io/component: kube-state-metrics
roleRef:
  apiGroup: {{ .Values.apiGroupVersion }}
  kind: ClusterRole
  name: {{.Release.Namespace}}:kube-state-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-kube-state-metrics
  namespace: {{.Release.Namespace}}
