apiVersion: v1
kind: Service
metadata:
  annotations:
    {{ .Values.prometheusDomain }}/scrape: "true"
  labels:
    app: prometheus
    component: "kube-state-metrics"
  name: prometheus-kube-state-metrics
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
    component: "kube-state-metrics"
  type: "ClusterIP"
