---
{{ if .Values.createClusterRoles }}
apiVersion: {{ .Values.rbacApiVersion }}
kind: ClusterRole
metadata:
  name: prometheus-kube-state-metrics
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
{{ end }}
---
apiVersion: {{ .Values.rbacApiVersion }}
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Namespace}}:prometheus-kube-state-metrics
roleRef:
  apiGroup: {{ .Values.apiGroupVersion }}
  kind: ClusterRole
  name: prometheus-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-kube-state-metrics
  namespace: {{.Release.Namespace}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-kube-state-metrics

---
apiVersion: {{ .Values.deploymentApiVersion }}
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: kube-state-metrics
  name: prometheus-kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: kube-state-metrics
  template:
    metadata:
      labels:
        app: prometheus
        component: kube-state-metrics
    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}
      serviceAccountName: prometheus-kube-state-metrics
      containers:
        - name: prometheus-kube-state-metrics
          image: "gcr.io/google_containers/kube-state-metrics:{{ .Values.kubeStateMetricsVersion }}"
          args:
            - --port=8080
            - --telemetry-port=8081
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.kubeStateMetricsCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.kubeStateMetricsMemoryRequest }}
          ports:
            - name: metrics
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{ .Values.prometheusDomain }}/scrape: "true"
  labels:
    app: prometheus
    component: "kube-state-metrics"
  name: prometheus-kube-state-metrics
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
    component: "kube-state-metrics"
  type: "ClusterIP"
