apiVersion: {{ .Values.deploymentApiVersion }}
kind: Deployment
metadata:
  name: prometheus-kube-state-metrics
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    com.lightbend.cloudflow/instance-id: {{ .Release.Name }}
    app.kubernetes.io/component: kube-state-metrics
spec:
  replicas: 1

  strategy:
    # Always Recreate to ensure we don't get duplicate metrics.
    type: Recreate
    # Needed for helm upgrade to succeed.
    rollingUpdate: null

  selector:
    matchLabels:
      app: prometheus
      component: kube-state-metrics

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        com.lightbend.cloudflow/instance-id: {{ .Release.Name }}
        app.kubernetes.io/component: kube-state-metrics
        # Deprecated - these should be removed eventually. Kept to support upgrades with the old labels.
        app: prometheus
        component: kube-state-metrics

    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}

      imagePullSecrets:
      - name: commercial-credentials

      serviceAccountName: prometheus-kube-state-metrics
      containers:
        - name: prometheus-kube-state-metrics
          image: {{ .Values.kubeStateMetricsImage }}:{{ .Values.kubeStateMetricsVersion }}
          args:
            - --port=8080
            - --namespace={{ .Values.kubeStateMetricsScrapeNamespaces }}
            - --telemetry-port=8081
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.kubeStateMetricsCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.kubeStateMetricsMemoryRequest }}
          ports:
            - name: metrics
              containerPort: 8080
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}