apiVersion: {{ .Values.daemonSetApiVersion }}
kind: DaemonSet
metadata:
  labels:
    app: prometheus
    component: node-exporter
  name: prometheus-node-exporter
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: prometheus
      component: node-exporter
  template:
    metadata:
      labels:
        app: prometheus
        component: node-exporter
    spec:
      serviceAccountName: "prometheus-node-exporter"
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}
      containers:
        - name: prometheus-node-exporter
          image: {{ .Values.nodeExporterImage }}:{{ .Values.nodeExporterVersion }}
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.nodeExporterCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.nodeExporterMemoryRequest }}
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.netdev.ignored-devices=^veth.*
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|host|var)($|/)
            - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
            - --no-collector.netstat
            - --no-collector.vmstat
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
