kind: Deployment
apiVersion: {{ .Values.deploymentApiVersion }}
metadata:
  labels:
    app: prometheus
    component: server
  name: prometheus-server
spec:
  replicas: 1

  strategy:
    # Always Recreate to ensure the PVs get released. It's not possible to have two replicas sharing a PV during deployment.
    type: Recreate

  selector:
    matchLabels:
      app: prometheus
      component: server
  template:
    metadata:
      labels:
        app: prometheus
        component: server
      annotations:
        {{ .Values.prometheusDomain }}/scrape: "true"
        {{ .Values.prometheusDomain }}/port: "9090"
    spec:
      serviceAccountName: prometheus-server

      securityContext:
      {{ if .Values.podUID }}
        runAsUser: {{ .Values.podUID }}
      {{ end }}

      initContainers:
        - name: setup
          image: {{ .Values.alpineImage }}:{{ .Values.alpineVersion }}
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest }}
          command:
            - /bin/sh
            - -c
          args:
            - mkdir -p /etc/config/rules;
              cp /etc/bare/prometheus.yml /etc/config/
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
            - mountPath: /etc/bare
              name: bare-prometheus

        # For vanilla K8s clusters, we need to match prometheus-data permissions to the prometheus user.
        # In prometheus 2.x, this is `65534`.
        # For Openshift the below will fail, but we can safely ignore it as Openshift remaps the user itself.
        - name: change-prometheus-data-volume-ownership
          image: {{ .Values.busyboxImage }}:{{ .Values.busyboxVersion }}
          command:
            - sh
            - -c
            - "chown -Rc 65534:65534 /data || true"
          volumeMounts:
            - name: prometheus-data-volume
              mountPath: /data
              subPath: prometheus-data

      imagePullSecrets:
        - name: commercial-credentials

      containers:
        - name: es-monitor-api
          image: {{ tpl .Values.esMonitorImage . }}:{{ .Values.esMonitorVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.esMonitorCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.esMonitorMemoryRequest }}
          args:
            - --configPath=/etc/config/
            - --storagePath=/monitor-data/
            - --staticConfig=/etc/es-monitor-api/static-rules.yml
            - --defaultMonitorsFile=/etc/es-monitor-api/default-monitors.json
            - --prometheusTemplate=/etc/es-monitor-api/prometheus.yml
            - --prometheusDomain={{ .Values.prometheusDomain }}
            - --alertmanagers={{ .Values.alertManagers }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: es-monitor-api-volume
              mountPath: /etc/es-monitor-api
            - name: prometheus-data-volume
              mountPath: /monitor-data
              subPath: monitor-data
          ports:
            - containerPort: 8180
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 8180
              scheme: HTTP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 8180
              scheme: HTTP
            initialDelaySeconds: 30

        - name: es-monitor-api-configmap-reload
          image: {{ .Values.configMapReloadImage }}:{{ .Values.configMapReloadVersion }}
          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.configmapReloadCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.configmapReloadMemoryRequest }}
          args:
          - --volume-dir=/etc/es-monitor-api
          - --webhook-url=http://127.0.0.1:8180/reload
          volumeMounts:
          - name: es-monitor-api-volume
            mountPath: /etc/es-monitor-api

        - name: prometheus-server
          image: {{ .Values.prometheusImage }}:{{ .Values.prometheusVersion }}

          resources:
            requests:
              cpu: {{ default .Values.defaultCPURequest .Values.prometheusCPURequest }}
              memory: {{ default .Values.defaultMemoryRequest .Values.prometheusMemoryRequest }}

          args:
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
            {{ if .Values.esConsoleURL -}}
            - --web.external-url={{ .Values.esConsoleURL }}/service/prometheus
            - --web.route-prefix=/
            {{ end }}
          ports:
            - containerPort: 9090

          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            timeoutSeconds: 30

          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            timeoutSeconds: 30
            initialDelaySeconds: 30

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: prometheus-data-volume
              mountPath: /data
              subPath: prometheus-data

      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: es-monitor-api-volume
          configMap:
            name: es-monitor-api
        - name: prometheus-data-volume
          {{ if or .Values.usePersistentVolumes (not .Values.useEmptyDirVolumes) }}
          persistentVolumeClaim:
            claimName: prometheus-storage
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: bare-prometheus
          configMap:
            name: bare-prometheus
