apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: server
  name: console-api-static-rules
data:
{{ (.Files.Glob "console-api/static-rules.yml").AsConfig | indent 2 }}
