apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9090
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: prometheus
