{{ if .Values.managePersistentVolumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ default .Values.defaultStorageClass .Values.prometheusStorageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheusVolumeSize }}
{{ end }}
