apiVersion: v1
kind: Service
metadata:
  name: console-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8180
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: prometheus
