{{ if .Values.usePersistentVolumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
spec:
  {{ if or .Values.defaultStorageClass .Values.prometheusStorageClass }}
  storageClassName: {{ default .Values.defaultStorageClass .Values.prometheusStorageClass }}
  {{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheusVolumeSize }}
{{ end }}
