apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Namespace }}-namespace-defaults
spec:
  limits:
  - defaultRequest:
      cpu: {{ .Values.defaultCPURequest }}
      memory: {{ .Values.defaultMemoryRequest }}
    type: Container
