apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: console-operator
  template:
    metadata:
      labels:
        name: console-operator
    spec:
      serviceAccountName: console-operator
      containers:
        - name: console-operator
          image: lightbend-docker-commercial-registry.bintray.io/enterprise-suite/console-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "console-operator"
