apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-operator
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
