---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: console-operator
  namespace: lightbend
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - console-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - console.lightbend.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: console-operator
  namespace: lightbend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: console-operator
subjects:
- kind: ServiceAccount
  name: console-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-operator
  namespace: lightbend
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: console-operator
  name: console-operator
  namespace: lightbend
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    name: console-operator
  name: console-operator
  namespace: lightbend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-operator
subjects:
- kind: ServiceAccount
  name: console-operator
  namespace: lightbend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-operator
  namespace: lightbend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: console-operator
  template:
    metadata:
      labels:
        name: console-operator
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: console-operator
        image: REPLACE_IMAGE
        imagePullPolicy: Always
        name: console-operator
      serviceAccountName: console-operator
