---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-operator
  namespace: lightbend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-operator
subjects:
- kind: ServiceAccount
  name: console-operator
  namespace: lightbend
