---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es-test-with-replication-controller
spec:
  replicas: 2
  selector:
    app: es-test-with-replication-controller
  template:
    metadata:
      name: es-test-with-replication-controller
      labels:
        app: es-test-with-replication-controller
      annotations:
        console-backend-e2e.io/scrape: "true"
    spec:
      containers:
        # source: https://github.com/lightbend/k8s-explore/tree/master/query/nan
        - name: es-test
          image: lightbend-docker-registry.bintray.io/enterprise-suite/es-test:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: metrics
