---
apiVersion: v1
kind: ReplicationController
metadata:
  name: es-test-with-replication-controller-via-service
spec:
  replicas: 2
  selector:
    app: es-test-with-replication-controller-via-service
  template:
    metadata:
      name: es-test-with-replication-controller-via-service
      labels:
        app: es-test-with-replication-controller-via-service
    spec:
      containers:
        # source: https://github.com/lightbend/k8s-explore/tree/master/query/nan
        - name: es-test
          image: lightbend-docker-registry.bintray.io/enterprise-suite/es-test:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: myport
---
apiVersion: v1
kind: Service
metadata:
  name: es-test-with-replication-controller-via-service
  annotations:
    console-backend-e2e.io/scrape: "true"
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: metrics
  selector:
    app: es-test-with-replication-controller-via-service
