#!/usr/bin/env bash

set -e

#
# This script releases enterprise-suite, an out-of-the-box monitoring solution for Kubernetes.
#

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
      --version)
      VERSION="$2"
      shift
      shift
      ;;
      --prometheus-version)
      PROMETHEUS_VERSION="$2"
      shift
      shift
      ;;
      --reactive-console-version)
      REACTIVE_CONSOLE_VERSION="$2"
      shift
      shift
      ;;
      *)
  esac
done

if [ "$VERSION" = "" ] || [ "$PROMETHEUS_VERSION" = "" ] || [ "$REACTIVE_CONSOLE_VERSION" = "" ]; then
  1>&2 echo "usage: $0 --version <es-version> --prometheus-version <prom-version> --reactive-console-version <cons-version>"
  exit 1
fi

cat enterprise-suite/Chart.yaml.template | \
  sed "s/0 #enterprise-suite-version/$VERSION/g" > enterprise-suite/Chart.yaml

cat enterprise-suite/values.yaml.template | \
  sed "s/0 #prometheus-version/$PROMETHEUS_VERSION/g" | \
  sed "s/0 #reactive-console-version/$REACTIVE_CONSOLE_VERSION/g" > enterprise-suite/values.yaml

helm package enterprise-suite -d docs

helm repo index docs --url https://lightbend.github.io/helm-charts

git add -A

git commit -m "Release enterprise-suite $VERSION"

