---
apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: REPLACE_IMAGE
  newName: lightbend-docker-registry.bintray.io/enterprise-suite/console-operator
  newTag: latest
kind: Kustomization
namespace: lightbend
resources:
- manifests/console-operator.yaml
